---
- name: rxvt-unicode-256color is installed
  apt:
    name: rxvt-unicode-256color

- name: Xdefaults are added
  blockinfile:
    block: "{{ lookup('file', 'Xdefaults') }}"
    dest: "/home/{{ username }}/.Xdefaults"
