---
- include: ubuntu.yml
  when: ansible_os_family == 'Ubuntu'

- include: arch.yml
  when: ansible_os_family == 'Archlinux'

- name: Spacemacs is checked out
  become: true
  become_user: "{{ username }}"
  git:
    repo: https://github.com/syl20bnr/spacemacs.git
    version: develop
    dest: "/home/{{ username }}/.emacs.d"
    depth: 1

- name: Spacemacs config is set up
  become: true
  become_user: "{{ username }}"
  copy:
    src: spacemacs
    dest: "/home/{{ username }}/.spacemacs"
    mode: 0644
