---
- include: ubuntu.yml
  when: ansible_os_family == 'Ubuntu'

- include: arch.yml
  when: ansible_os_family == 'ArchLinux'

- name: Xdefaults file exists
  command: "touch /home/{{ username }}/.Xdefaults"
  args:
    creates: "/home/{{ username }}/.Xdefaults"

- name: Xdefaults are added
  become: true
  become_user: "{{ username }}"
  blockinfile:
    block: "{{ lookup('file', 'Xdefaults') }}"
    dest: "/home/{{ username }}/.Xdefaults"
    marker: "; {mark} I3"

- name: Gtk 2 theme is set up
  become: true
  become_user: "{{ username }}"
  copy:
    src: gtkrc-2.0
    dest: "/home/{{ username }}/.gtkrc-2.0"

- name: Gtk 3 theme is set up
  become: true
  become_user: "{{ username }}"
  copy:
    src: gtk3-settings.ini
    dest: "/home/{{ username }}/.config/gtk-3.0/settings.ini"

- name: i3 config directory exists
  become: true
  become_user: "{{ username }}"
  file:
    path: "/home/{{ username }}/.config/i3"
    state: directory

- name: i3 config is set up
  become: true
  become_user: "{{ username }}"
  copy:
    src: config
    dest: "/home/{{ username }}/.config/i3/config"

- name: i3status config is set up
  become: true
  become_user: "{{ username }}"
  copy:
    src: i3status.conf
    dest: "/home/{{ username }}/.i3status.conf"

- name: i3 wallpaper is installed
  become: true
  become_user: "{{ username }}"
  copy:
    src: wallpaper.jpg
    dest: "/home/{{ username }}/.config/i3/wallpaper.jpg"
