---
- include: ubuntu.yml
  when: ansible_os_family == 'Ubuntu'

- include: arch.yml
  when: ansible_os_family == 'Archlinux'

- name: Tmux config is set up
  become: true
  become_user: "{{ username }}"
  copy:
    src: tmux.conf
    dest: "/home/{{ username }}/.tmux.conf"
    mode: 0644
